// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afmefzeubvvlnvxaxfni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmbWVmemV1YnZ2bG52eGF4Zm5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODg4MTIsImV4cCI6MjA2OTU2NDgxMn0.og5iCVZF0dIJoDuNJG_nhyDXGzRLaKfuRzkdvIGaCbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});